### PR TITLE
Run client handler functions in separate thread

### LINKED ISSUE #164: [ROS2] Custom types and parameters fail
**Description**
Right now, we have a custom service type that we do not really care about. The problem is that the bridge tries to get it and since it does not recognise the type it throws errors on the terminal as well as warnings on the ros log. While this happens we lose messages for about 3 seconds until it comes back to life.

Log window:
image

- Version: Latest main
- Platform: Ubuntu 22.04 (ROS humble)

### PR DESCRIPTION
**Pull request by achim-k**
**Public-Facing Changes**
- Run client handlers in separate thread

**Description**
Builds on top of #156 

So far we have executed client handler functions in the websocket server thread. This could cause issues with clients not receiving messages anymore while a longer-running handler function was executing. This PR fixes this by handler functions being executed in a separate thread.

Fixes #164 
Fixes FG-2029

### CODE REVIEW

File: foxglove_bridge_base/include/foxglove_bridge/common.hpp [hunk 1]
```diff
@@ -74,26 +75,28 @@ struct ClientMessage {
...
-                const ClientAdvertisement& advertisement, size_t dataLength, const uint8_t* data)
+                const ClientAdvertisement& advertisement, size_t dataLength, const uint8_t* rawData)
       : logTime(logTime)
       , publishTime(publishTime)
       , sequence(sequence)
       , advertisement(advertisement)
       , dataLength(dataLength)
-      , data(data) {}
+      , data(dataLength) {
+    std::memcpy(data.data(), rawData, dataLength);
```
Comment (jhurliman) [inline foxglove_bridge_base/include/foxglove_bridge/common.hpp:90]: Is the additional copy worth it? We should test on a low-power platform like a Jetson Nano.

File: foxglove_bridge_base/include/foxglove_bridge/common.hpp [hunk 2]
```diff
@@ -74,26 +75,28 @@ struct ClientMessage {
...
-  const uint8_t* data;
+  std::vector<uint8_t> data;
 
   ClientMessage(uint64_t logTime, uint64_t publishTime, uint32_t sequence,
-                const ClientAdvertisement& advertisement, size_t dataLength, const uint8_t* data)
+                const ClientAdvertisement& advertisement, size_t dataLength, const uint8_t* rawData)
       : logTime(logTime)
       , publishTime(publishTime)
       , sequence(sequence)
       , advertisement(advertisement)
```
Comment (jhurliman) [inline foxglove_bridge_base/include/foxglove_bridge/common.hpp:87]: This is now a copy, but I'm assuming `ClientAdvertisement` is relative cheap to copy?

File: foxglove_bridge_base/include/foxglove_bridge/common.hpp (hunk 1 above)
Comment (achim-k) [reply foxglove_bridge_base/include/foxglove_bridge/common.hpp:90]: We have to do a copy now since we call the handler in a different thread and the pointer to the original data is likely not valid anymore.

File: foxglove_bridge_base/include/foxglove_bridge/common.hpp (hunk 2 above)
Comment (achim-k) [reply foxglove_bridge_base/include/foxglove_bridge/common.hpp:87]: Yes I think so too. At this stage I would rather have an extra copy then some hard to find bug. But yes, there is definitely potential for improvement later on

**Review by jhurliman — APPROVED** [review]
