### PR TITLE
Assume publisher qos depth of 1 if the middleware reports the qos history as unknown

### LINKED ISSUE #238: ROS2 static transforms partially propagating through the web bridge to studio
**Description**

- Version: Foxglove Studio 1.55.0 / Foxglove Web Bridge 0.5.3
- Platform: Foxglove Studio on OSX, Foxglove Web Bridge on Linux
- Data source: Only affects streaming from a live system. Does not appear to affect loading a MCAP file directly into studio.

**Steps To Reproduce**

Take a look at this simple launch file that sets up a basic static transform hierarchy:
https://gist.github.com/asymingt/1d833ac9857ecba36eb2fa523137a7ba

Launch like this from a ROS2 rolling distribution:
```
$ ros2 launch static_frame_issue.launch.py
```

Confirm you see the correct frames with:
```
$ ros2 topic echo /tf_static
transforms:
- header:
    stamp:
      sec: 1687902344
      nanosec: 58697684
    frame_id: bar_child1
  child_frame_id: bar_child1_grandchild
  transform:
    translation:
      x: 0.0
      y: 0.0
      z: 0.0
    rotation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
---
transforms:
- header:
    stamp:
      sec: 1687902344
      nanosec: 55601655
    frame_id: bar
  child_frame_id: foo
  transform:
    translation:
      x: 0.0
      y: 0.0
      z: 0.0
    rotation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
---
transforms:
- header:
    stamp:
      sec: 1687902344
      nanosec: 54859102
    frame_id: bar
  child_frame_id: bar_child1
  transform:
    translation:
      x: 0.5
      y: 1.0
      z: 2.0
    rotation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
---
transforms:
- header:
    stamp:
      sec: 1687902344
      nanosec: 56240568
    frame_id: bar_child2
  child_frame_id: bar_child2_grandchild
  transform:
    translation:
      x: 0.0
      y: 0.0
      z: 0.0
    rotation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
---
transforms:
- header:
    stamp:
      sec: 1687902344
      nanosec: 56478622
    frame_id: bar
  child_frame_id: bar_child2
  transform:
    translation:
      x: 0.5
      y: -1.0
      z: 2.0
    rotation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
---
```

**Expected Behavior**

I would expect to see a transform hierarchy that looks like this, in both the `Transforms` section of the `3D` panel, as well as in the 3D visualization itself:

```
+ baz
  + bar
    + bar_child1
      + bar_child1_grandchild
    + bar_child2
      + bar_child2_grandchild
    + foo
```

However, only a subset of the frames are actually received and drawn. So, for example sometimes you see this:

```
+ baz
  + bar
    + bar_child1
      + bar_child1_grandchild
```

And sometimes you see this:

```
+ baz
  + bar
    + bar_child2
      + bar_child2_grandchild
```

Example screenshot of the problematic `Transforms` panel:

Screen Shot 2023-06-27 at 2 30 44 PM

Example screenshot of the problematic `3D` window:

Screen Shot 2023-06-27 at 2 32 04 PM

### PR DESCRIPTION
**Pull request by achim-k**
### Public-Facing Changes

Assume publisher qos depth of 1 if the middleware reports the qos history as unknown

### Description
Some RMWs do not report history information of a publisher endpoint in which case the history depth is reported as 0. We internally use this depth to calculate an appropriate depth for the subscription, which uses the `KeepLast(depth)` history policy.
In case a publisher's history depth is reported as 0, we assume a depth of 1 so that the final history depth is at least equal to the number of publishers. This covers the case where there are multiple transient_local publishers with a depth of 1 (e.g. multiple tf_static transform broadcasters). Before this PR, a user would have to manually specify a `min_qos_depth` of N when having N tf_static broadcasters.

This PR also increases the max qos depth default value, 10 seemed very low. I'm not sure anymore why we added an upper limit in the first place. Additionally, a warning is logged when the upper limit is reached.

Fixes #238 
See also https://github.com/foxglove/ros-foxglove-bridge/issues/208

### CODE REVIEW

File: foxglove_bridge_base/src/test/test_client.cpp [hunk 1]
```diff
@@ -12,43 +12,37 @@ namespace foxglove {
 constexpr auto DEFAULT_TIMEOUT = std::chrono::seconds(5);
 
 std::vector<uint8_t> connectClientAndReceiveMsg(const std::string& uri,
-                                                const std::string& topic_name) {
+                                                const std::string& topicName) {
   // Set up text message handler to resolve the promise when the topic is advertised
-  foxglove::Client<websocketpp::config::asio_client> wsClient;
+  auto wsClient = std::make_shared<foxglove::Client<websocketpp::config::asio_client>>();
```
Comment (jtbandes) [inline foxglove_bridge_base/src/test/test_client.cpp:17]: Why does this need to be a shared_ptr? Would unique_ptr work? I don't see the ownership being actually shared anywhere?

File: foxglove_bridge_base/src/test/test_client.cpp [hunk 2]
```diff
@@ -118,6 +112,30 @@ std::future<Service> waitForService(std::shared_ptr<ClientInterface> client,
   return future;
 }
 
+std::future<Channel> waitForChannel(std::shared_ptr<ClientInterface> client,
+                                    const std::string& topicName) {
+  auto promise = std::make_shared<std::promise<Channel>>();
```
Comment (jtbandes) [inline foxglove_bridge_base/src/test/test_client.cpp:117]: Why shared_ptr? The std::promise example code seems to allocate a promise on the stack and still move it into a thread or lambda.

**Review by jtbandes — APPROVED** [review]

File: foxglove_bridge_base/src/test/test_client.cpp (hunk 1 above)
Comment (achim-k) [reply foxglove_bridge_base/src/test/test_client.cpp:17]: You are right, will see what I can do. Can just pass a raw pointer to `waitForChannel` then

File: foxglove_bridge_base/src/test/test_client.cpp (hunk 2 above)
Comment (achim-k) [reply foxglove_bridge_base/src/test/test_client.cpp:117]: I remember that John and I had some issues with that but don't remember exactly why. Will see what I can do once I created a new release
