### PR TITLE
Make ROS1 service type retrieval more robust

### LINKED ISSUE #262: Failing to retrieve service type, brings node down
**Description**
The node aborts during repeated "Failed to retrieve service type" and crashes the node.

```
SUMMARY
========

PARAMETERS
 * /foxglove_bridge/address: 0.0.0.0
2023-09-01T21:43:49.718834923Z  * /foxglove_bridge/asset_uri_allowlist: ['package://(/?\\...
2023-09-01T21:43:49.718837287Z  * /foxglove_bridge/capabilities: ['clientPublish',...
 * /foxglove_bridge/certfile: 
 * /foxglove_bridge/client_topic_whitelist: ['.*']
2023-09-01T21:43:49.718846455Z  * /foxglove_bridge/keyfile: 
 * /foxglove_bridge/max_update_ms: 5000
 * /foxglove_bridge/param_whitelist: ['.*']
 * /foxglove_bridge/port: 8765
 * /foxglove_bridge/send_buffer_limit: 10000000
 * /foxglove_bridge/service_whitelist: ['.*']
 * /foxglove_bridge/tls: False
2023-09-01T21:43:49.718861954Z  * /foxglove_bridge/topic_whitelist: ['.*']
 * /foxglove_nodelet_manager/num_worker_threads: 0
 * /rosdistro: noetic
2023-09-01T21:43:49.718868607Z  * /rosversion: 1.16.0

NODES
  /
    foxglove_bridge (nodelet/nodelet)
    foxglove_nodelet_manager (nodelet/nodelet)

ROS_MASTER_URI=http://hood1-1-rios-roscore-service:80/
]2;/opt/rios/install/share/foxglove_bridge/launch/foxglove_bridge.launch http://hood1-1-rios-roscore-service:80/
process[foxglove_nodelet_manager-1]: started with pid [68]
process[foxglove_bridge-2]: started with pid [69]
2023-09-01T21:43:49.954738356Z [ERROR] [1693604629.954637736]: Failed to retrieve service type or service description of service /rviz_msiraider_455523_4051231953047898198/get_loggers: std::future_error: Broken promise
[ERROR] [1693604629.960421416]: Failed to retrieve service type or service description of service /rviz_msiraider_455523_4051231953047898198/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604629.963452575]: Failed to retrieve service type or service description of service /rviz_msiraider_455523_4051231953047898198/reload_shaders: std::future_error: Broken promise
[ERROR] [1693604629.966846903]: Failed to retrieve service type or service description of service /rviz_msiraider_455523_4051231953047898198/load_config: std::future_error: Broken promise
[ERROR] [1693604629.970424157]: Failed to retrieve service type or service description of service /rviz_msiraider_455523_4051231953047898198/load_config_discarding_changes: std::future_error: Broken promise
[ERROR] [1693604629.974170433]: Failed to retrieve service type or service description of service /rviz_msiraider_455523_4051231953047898198/save_config: std::future_error: Broken promise
[ERROR] [1693604629.976027506]: Failed to retrieve service type or service description of service /rqt_gui_cpp_node_3355783/get_loggers: std::future_error: Broken promise
[ERROR] [1693604629.977745424]: Failed to retrieve service type or service description of service /rqt_gui_cpp_node_3355783/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604629.982635479]: Failed to retrieve service type or service description of service /rqt_gui_cpp_node_3360882/get_loggers: std::future_error: Broken promise
[ERROR] [1693604629.985879822]: Failed to retrieve service type or service description of service /rqt_gui_cpp_node_3360882/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604629.995735004]: Failed to retrieve service type or service description of service /tf_echo_1693005407704472780/get_loggers: std::future_error: Broken promise
[ERROR] [1693604629.997922693]: Failed to retrieve service type or service description of service /tf_echo_1693005407704472780/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604630.002444470]: Failed to retrieve service type or service description of service /rviz_msiraider_475863_1805560526383919607/get_loggers: std::future_error: Broken promise
[ERROR] [1693604630.007448601]: Failed to retrieve service type or service description of service /rviz_msiraider_475863_1805560526383919607/set_logger_level: std::future_error: Broken promise
2023-09-01T21:43:50.013426630Z [ERROR] [1693604630.013370403]: Failed to retrieve service type or service description of service /rviz_msiraider_475863_1805560526383919607/reload_shaders: std::future_error: Broken promise
[ERROR] [1693604630.018472310]: Failed to retrieve service type or service description of service /rviz_msiraider_475863_1805560526383919607/load_config: std::future_error: Broken promise
[ERROR] [1693604630.023164429]: Failed to retrieve service type or service description of service /rviz_msiraider_475863_1805560526383919607/load_config_discarding_changes: std::future_error: Broken promise
[ERROR] [1693604630.028526369]: Failed to retrieve service type or service description of service /rviz_msiraider_475863_1805560526383919607/save_config: std::future_error: Broken promise
[ERROR] [1693604630.033903217]: Failed to retrieve service type or service description of service /rqt_gui_cpp_node_68845/get_loggers: std::future_error: Broken promise
[ERROR] [1693604630.038839359]: Failed to retrieve service type or service description of service /rqt_gui_cpp_node_68845/set_logger_level: std::future_error: Broken promise
[ WARN] [1693604630.291370231]: Failed to retrieve type of service /rqt_gui_cpp_node_11371/get_loggers
2023-09-01T21:43:50.543664253Z [ WARN] [1693604630.543572709]: Failed to retrieve type of service /rqt_gui_cpp_node_11371/set_logger_level
[ WARN] [1693604630.795988773]: Failed to retrieve type of service /rqt_gui_cpp_node_15179/get_loggers
[ WARN] [1693604631.049000466]: Failed to retrieve type of service /rqt_gui_cpp_node_15179/set_logger_level
[ WARN] [1693604631.302035504]: Failed to retrieve type of service /rqt_gui_cpp_node_15179/compressed/set_parameters
[ERROR] [1693604631.305001208]: Failed to retrieve service type or service description of service /tf_echo_1693329846940349580/get_loggers: std::future_error: Broken promise
[ERROR] [1693604631.307799466]: Failed to retrieve service type or service description of service /tf_echo_1693329846940349580/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604631.312068543]: Failed to retrieve service type or service description of service /rviz_msiraider_613058_4222886344543863053/get_loggers: std::future_error: Broken promise
[ERROR] [1693604631.315257622]: Failed to retrieve service type or service description of service /rviz_msiraider_613058_4222886344543863053/set_logger_level: std::future_error: Broken promise
2023-09-01T21:43:51.319103386Z [ERROR] [1693604631.318751839]: Failed to retrieve service type or service description of service /rviz_msiraider_613058_4222886344543863053/reload_shaders: std::future_error: Broken promise
[ERROR] [1693604631.322952897]: Failed to retrieve service type or service description of service /rviz_msiraider_613058_4222886344543863053/load_config: std::future_error: Broken promise
[ERROR] [1693604631.327608327]: Failed to retrieve service type or service description of service /rviz_msiraider_613058_4222886344543863053/load_config_discarding_changes: std::future_error: Broken promise
[ERROR] [1693604631.331009648]: Failed to retrieve service type or service description of service /rviz_msiraider_613058_4222886344543863053/save_config: std::future_error: Broken promise
[ERROR] [1693604631.379363711]: Failed to retrieve service type or service description of service /rostopic_614368_1693332654733/get_loggers: std::future_error: Broken promise
[ERROR] [1693604631.383728559]: Failed to retrieve service type or service description of service /rostopic_614368_1693332654733/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604631.386775559]: Failed to retrieve service type or service description of service /rviz_msiraider_618543_7783352244266021340/get_loggers: std::future_error: Broken promise
[ERROR] [1693604631.390348856]: Failed to retrieve service type or service description of service /rviz_msiraider_618543_7783352244266021340/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604631.393720982]: Failed to retrieve service type or service description of service /rviz_msiraider_618543_7783352244266021340/reload_shaders: std::future_error: Broken promise
[ERROR] [1693604631.397023165]: Failed to retrieve service type or service description of service /rviz_msiraider_618543_7783352244266021340/load_config: std::future_error: Broken promise
[ERROR] [1693604631.400547830]: Failed to retrieve service type or service description of service /rviz_msiraider_618543_7783352244266021340/load_config_discarding_changes: std::future_error: Broken promise
[ WARN] [1693604633.884170701]: Could not find package 'camera_control_msgs' in srv paths!
[ERROR] [1693604633.884195017]: Failed to retrieve type information for service '/qc_camera1/get_cam_properties' of type 'camera_control_msgs/GetCamProperties'
[ WARN] [1693604633.887191851]: Could not find package 'arena_camera_ros' in srv paths!
2023-09-01T21:43:53.887251244Z [ERROR] [1693604633.887212631]: Failed to retrieve type information for service '/qc_camera1/toggle_stream' of type 'arena_camera_ros/ToggleCameraStream'
[ WARN] [1693604633.917033031]: Could not find package 'camera_control_msgs' in srv paths!
[ERROR] [1693604633.917065743]: Failed to retrieve type information for service '/qc_camera2/set_binning' of type 'camera_control_msgs/SetBinning'
2023-09-01T21:43:53.920068057Z [ WARN] [1693604633.920025937]: Could not find package 'camera_control_msgs' in srv paths!
[ERROR] [1693604633.920049983]: Failed to retrieve type information for service '/qc_camera2/set_exposure' of type 'camera_control_msgs/SetExposure'
2023-09-01T21:43:53.922878037Z [ WARN] [1693604633.922837389]: Could not find package 'camera_control_msgs' in srv paths!
[ERROR] [1693604633.922858760]: Failed to retrieve type information for service '/qc_camera2/set_gain' of type 'camera_control_msgs/SetGain'
[ WARN] [1693604633.928546769]: Could not find package 'camera_control_msgs' in srv paths!
[ERROR] [1693604633.928573579]: Failed to retrieve type information for service '/qc_camera2/set_gamma' of type 'camera_control_msgs/SetGamma'
[ WARN] [1693604633.931902503]: Could not find package 'camera_control_msgs' in srv paths!
[ERROR] [1693604633.931927521]: Failed to retrieve type information for service '/qc_camera2/get_cam_properties' of type 'camera_control_msgs/GetCamProperties'
[ WARN] [1693604633.934509107]: Could not find package 'arena_camera_ros' in srv paths!
[ERROR] [1693604633.934533724]: Failed to retrieve type information for service '/qc_camera2/toggle_stream' of type 'arena_camera_ros/ToggleCameraStream'
[ WARN] [1693604634.000754093]: Could not find package 'camera_control_msgs' in srv paths!
[ERROR] [1693604634.000793578]: Failed to retrieve type information for service '/qc_camera3/set_binning' of type 'camera_control_msgs/SetBinning'
[ WARN] [1693604634.006043265]: Could not find package 'camera_control_msgs' in srv paths!
[ERROR] [1693604634.006080195]: Failed to retrieve type information for service '/qc_camera3/set_exposure' of type 'camera_control_msgs/SetExposure'
2023-09-01T21:43:54.010520507Z [ WARN] [1693604634.010460173]: Could not find package 'camera_control_msgs' in srv paths!
[ERROR] [1693604634.010488476]: Failed to retrieve type information for service '/qc_camera3/set_gain' of type 'camera_control_msgs/SetGain'
[ WARN] [1693604634.012819628]: Could not find package 'camera_control_msgs' in srv paths!
[ERROR] [1693604634.012843794]: Failed to retrieve type information for service '/qc_camera3/set_gamma' of type 'camera_control_msgs/SetGamma'
2023-09-01T21:43:54.015401124Z [ WARN] [1693604634.015358714]: Could not find package 'camera_control_msgs' in srv paths!
[ERROR] [1693604634.015384623]: Failed to retrieve type information for service '/qc_camera3/get_cam_properties' of type 'camera_control_msgs/GetCamProperties'
2023-09-01T21:43:54.017577041Z [ WARN] [1693604634.017520243]: Could not find package 'arena_camera_ros' in srv paths!
[ERROR] [1693604634.017543197]: Failed to retrieve type information for service '/qc_camera3/toggle_stream' of type 'arena_camera_ros/ToggleCameraStream'
[ WARN] [1693604634.888113285]: Failed to retrieve type of service /rostopic_3080030_1693521791615/get_loggers
2023-09-01T21:43:55.162104952Z [ WARN] [1693604635.161994142]: Failed to retrieve type of service /rqt_gui_cpp_node_54672/get_loggers
[ WARN] [1693604635.414474287]: Failed to retrieve type of service /rqt_gui_cpp_node_54672/set_logger_level
2023-09-01T21:43:55.493921674Z [ERROR] [1693604635.493826935]: Failed to retrieve service type or service description of service /azure1/k4a_nodelet_manager/get_loggers: std::future_error: Broken promise
[ERROR] [1693604635.495109848]: Failed to retrieve service type or service description of service /azure1/k4a_nodelet_manager/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604635.496578403]: Failed to retrieve service type or service description of service /azure1/k4a_nodelet_manager/load_nodelet: std::future_error: Broken promise
[ERROR] [1693604635.497926219]: Failed to retrieve service type or service description of service /azure1/k4a_nodelet_manager/unload_nodelet: std::future_error: Broken promise
2023-09-01T21:43:55.499340081Z [ERROR] [1693604635.499303221]: Failed to retrieve service type or service description of service /azure1/k4a_nodelet_manager/list: std::future_error: Broken promise
[ERROR] [1693604635.500588469]: Failed to retrieve service type or service description of service /robot_2_dx_motion_interface/get_loggers: std::future_error: Broken promise
[ WARN] [1693604635.751974429]: Failed to retrieve type of service /robot_2_dx_motion_interface/set_logger_level
[ERROR] [1693604635.754514737]: Failed to retrieve service type or service description of service /robot_2_fanuc_rmi_client/get_loggers: std::future_error: Broken promise
[ERROR] [1693604635.759561830]: Failed to retrieve service type or service description of service /robot_2_fanuc_rmi_client/set_logger_level: std::future_error: Broken promise
2023-09-01T21:43:55.765559225Z [ERROR] [1693604635.765512447]: Failed to retrieve service type or service description of service /R2_VeneerCornerObserver/get_loggers: std::future_error: Broken promise
[ERROR] [1693604635.766427602]: Failed to retrieve service type or service description of service /R2_VeneerCornerObserver/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604635.767290950]: Failed to retrieve service type or service description of service /robot_1_dx_motion_interface/get_loggers: std::future_error: Broken promise
[ERROR] [1693604635.768171179]: Failed to retrieve service type or service description of service /robot_1_dx_motion_interface/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604635.769066327]: Failed to retrieve service type or service description of service /robot_1_fanuc_rmi_client/get_loggers: std::future_error: Broken promise
[ERROR] [1693604635.773180531]: Failed to retrieve service type or service description of service /robot_1_fanuc_rmi_client/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604635.924435023]: Failed to retrieve service type or service description of service /rviz_msiraider_455523_4051231953047898198/get_loggers: std::future_error: Broken promise
[ERROR] [1693604635.930194718]: Failed to retrieve service type or service description of service /rviz_msiraider_455523_4051231953047898198/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604635.935104139]: Failed to retrieve service type or service description of service /rviz_msiraider_455523_4051231953047898198/reload_shaders: std::future_error: Broken promise
[ERROR] [1693604635.939061535]: Failed to retrieve service type or service description of service /rviz_msiraider_455523_4051231953047898198/load_config: std::future_error: Broken promise
[ERROR] [1693604635.942793704]: Failed to retrieve service type or service description of service /rviz_msiraider_455523_4051231953047898198/load_config_discarding_changes: std::future_error: Broken promise
2023-09-01T21:43:55.946994611Z [ERROR] [1693604635.946937263]: Failed to retrieve service type or service description of service /rviz_msiraider_455523_4051231953047898198/save_config: std::future_error: Broken promise
[ERROR] [1693604635.948405397]: Failed to retrieve service type or service description of service /rqt_gui_cpp_node_3355783/get_loggers: std::future_error: Broken promise
2023-09-01T21:43:55.949828576Z [ERROR] [1693604635.949785685]: Failed to retrieve service type or service description of service /rqt_gui_cpp_node_3355783/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604635.952033509]: Failed to retrieve service type or service description of service /rqt_gui_cpp_node_3360882/get_loggers: std::future_error: Broken promise
[ERROR] [1693604635.953121563]: Failed to retrieve service type or service description of service /rqt_gui_cpp_node_3360882/set_logger_level: std::future_error: Broken promise
2023-09-01T21:43:55.955427967Z [ERROR] [1693604635.955358255]: Failed to retrieve service type or service description of service /tf_echo_1693005407704472780/get_loggers: std::future_error: Broken promise
[ERROR] [1693604635.958549357]: Failed to retrieve service type or service description of service /tf_echo_1693005407704472780/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604635.963378256]: Failed to retrieve service type or service description of service /rviz_msiraider_475863_1805560526383919607/get_loggers: std::future_error: Broken promise
[ERROR] [1693604635.967455169]: Failed to retrieve service type or service description of service /rviz_msiraider_475863_1805560526383919607/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604635.973375127]: Failed to retrieve service type or service description of service /rviz_msiraider_475863_1805560526383919607/reload_shaders: std::future_error: Broken promise
[ERROR] [1693604635.978929322]: Failed to retrieve service type or service description of service /rviz_msiraider_475863_1805560526383919607/load_config: std::future_error: Broken promise
[ERROR] [1693604635.983714979]: Failed to retrieve service type or service description of service /rviz_msiraider_475863_1805560526383919607/load_config_discarding_changes: std::future_error: Broken promise
[ERROR] [1693604635.988177192]: Failed to retrieve service type or service description of service /rviz_msiraider_475863_1805560526383919607/save_config: std::future_error: Broken promise
[ WARN] [1693604636.240285112]: Failed to retrieve type of service /rqt_gui_cpp_node_68845/get_loggers
[ERROR] [1693604636.245580837]: Failed to retrieve service type or service description of service /rqt_gui_cpp_node_68845/set_logger_level: std::future_error: Broken promise
[ WARN] [1693604636.497235276]: Failed to retrieve type of service /rqt_gui_cpp_node_11371/get_loggers
[ WARN] [1693604636.750249946]: Failed to retrieve type of service /rqt_gui_cpp_node_11371/set_logger_level
[ WARN] [1693604637.002703832]: Failed to retrieve type of service /rqt_gui_cpp_node_15179/get_loggers
[ WARN] [1693604637.255063360]: Failed to retrieve type of service /rqt_gui_cpp_node_15179/set_logger_level
[ WARN] [1693604637.507601486]: Failed to retrieve type of service /rqt_gui_cpp_node_15179/compressed/set_parameters
[ERROR] [1693604637.510493360]: Failed to retrieve service type or service description of service /tf_echo_1693329846940349580/get_loggers: std::future_error: Broken promise
[ERROR] [1693604637.512003444]: Failed to retrieve service type or service description of service /tf_echo_1693329846940349580/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604637.515548539]: Failed to retrieve service type or service description of service /rviz_msiraider_613058_4222886344543863053/get_loggers: std::future_error: Broken promise
[ERROR] [1693604637.518957915]: Failed to retrieve service type or service description of service /rviz_msiraider_613058_4222886344543863053/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604637.523424577]: Failed to retrieve service type or service description of service /rviz_msiraider_613058_4222886344543863053/reload_shaders: std::future_error: Broken promise
[ERROR] [1693604637.526815428]: Failed to retrieve service type or service description of service /rviz_msiraider_613058_4222886344543863053/load_config: std::future_error: Broken promise
[ERROR] [1693604637.530761303]: Failed to retrieve service type or service description of service /rviz_msiraider_613058_4222886344543863053/load_config_discarding_changes: std::future_error: Broken promise
[ERROR] [1693604637.534517817]: Failed to retrieve service type or service description of service /rviz_msiraider_613058_4222886344543863053/save_config: std::future_error: Broken promise
[ERROR] [1693604637.537352724]: Failed to retrieve service type or service description of service /rostopic_614368_1693332654733/get_loggers: std::future_error: Broken promise
[ERROR] [1693604642.534917374]: Failed to retrieve service type or service description of service /tf_echo_1693329846940349580/get_loggers: std::future_error: Broken promise
[ERROR] [1693604642.535978898]: Failed to retrieve service type or service description of service /tf_echo_1693329846940349580/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604642.539597401]: Failed to retrieve service type or service description of service /rviz_msiraider_613058_4222886344543863053/get_loggers: std::future_error: Broken promise
[ERROR] [1693604642.542813721]: Failed to retrieve service type or service description of service /rviz_msiraider_613058_4222886344543863053/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604642.546250369]: Failed to retrieve service type or service description of service /rviz_msiraider_613058_4222886344543863053/reload_shaders: std::future_error: Broken promise
[ERROR] [1693604642.549297780]: Failed to retrieve service type or service description of service /rviz_msiraider_613058_4222886344543863053/load_config: std::future_error: Broken promise
[ERROR] [1693604642.553177488]: Failed to retrieve service type or service description of service /rviz_msiraider_613058_4222886344543863053/load_config_discarding_changes: std::future_error: Broken promise
[ERROR] [1693604642.556038374]: Failed to retrieve service type or service description of service /rviz_msiraider_613058_4222886344543863053/save_config: std::future_error: Broken promise
[ERROR] [1693604642.558357262]: Failed to retrieve service type or service description of service /rostopic_614368_1693332654733/get_loggers: std::future_error: Broken promise
[ERROR] [1693604642.560864648]: Failed to retrieve service type or service description of service /rostopic_614368_1693332654733/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604642.564076470]: Failed to retrieve service type or service description of service /rviz_msiraider_618543_7783352244266021340/get_loggers: std::future_error: Broken promise
[ERROR] [1693604642.567137526]: Failed to retrieve service type or service description of service /rviz_msiraider_618543_7783352244266021340/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604642.569462505]: Failed to retrieve service type or service description of service /rviz_msiraider_618543_7783352244266021340/reload_shaders: std::future_error: Broken promise
[ERROR] [1693604642.572294607]: Failed to retrieve service type or service description of service /rviz_msiraider_618543_7783352244266021340/load_config: std::future_error: Broken promise
[ERROR] [1693604642.575269139]: Failed to retrieve service type or service description of service /rviz_msiraider_618543_7783352244266021340/load_config_discarding_changes: std::future_error: Broken promise
[ERROR] [1693604642.578592703]: Failed to retrieve service type or service description of service /rviz_msiraider_618543_7783352244266021340/save_config: std::future_error: Broken promise
[ WARN] [1693604642.829554920]: Failed to retrieve type of service /rqt_gui_cpp_node_19923/get_loggers
[ WARN] [1693604643.082882946]: Failed to retrieve type of service /rqt_gui_cpp_node_19923/set_logger_level
[ WARN] [1693604643.335065919]: Failed to retrieve type of service /rqt_gui_cpp_node_11730/get_loggers
[ WARN] [1693604643.587460093]: Failed to retrieve type of service /rqt_gui_cpp_node_11730/set_logger_level
[ WARN] [1693604643.839907638]: Failed to retrieve type of service /rqt_gui_cpp_node_11730/compressed/set_parameters
[ERROR] [1693604643.845982721]: Failed to retrieve service type or service description of service /LogCommanderTester_cpp/get_loggers: std::future_error: Broken promise
[ERROR] [1693604643.850509587]: Failed to retrieve service type or service description of service /LogCommanderTester_cpp/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604643.853895659]: Failed to retrieve service type or service description of service /rviz_msiraider_712938_3675954756021939125/get_loggers: std::future_error: Broken promise
[ERROR] [1693604643.857126998]: Failed to retrieve service type or service description of service /rviz_msiraider_712938_3675954756021939125/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604643.861228538]: Failed to retrieve service type or service description of service /rviz_msiraider_712938_3675954756021939125/reload_shaders: std::future_error: Broken promise
[ERROR] [1693604643.865680351]: Failed to retrieve service type or service description of service /rviz_msiraider_712938_3675954756021939125/load_config: std::future_error: Broken promise
[ERROR] [1693604643.870866328]: Failed to retrieve service type or service description of service /rviz_msiraider_712938_3675954756021939125/load_config_discarding_changes: std::future_error: Broken promise
[ERROR] [1693604643.874622261]: Failed to retrieve service type or service description of service /rviz_msiraider_712938_3675954756021939125/save_config: std::future_error: Broken promise
[ERROR] [1693604643.994334548]: Failed to retrieve service type or service description of service /rviz_1693500241430558177/get_loggers: std::future_error: Broken promise
[ERROR] [1693604644.007334375]: Failed to retrieve service type or service description of service /rviz_1693500241430558177/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604644.026646084]: Failed to retrieve service type or service description of service /rviz_1693500241430558177/reload_shaders: std::future_error: Broken promise
[ERROR] [1693604644.053180772]: Failed to retrieve service type or service description of service /rviz_1693500241430558177/load_config: std::future_error: Broken promise
[ERROR] [1693604644.172584975]: Failed to retrieve service type or service description of service /rviz_1693500241430558177/load_config_discarding_changes: std::future_error: Broken promise
[ERROR] [1693604644.290143928]: Failed to retrieve service type or service description of service /rviz_1693500241430558177/save_config: std::future_error: Broken promise
[ WARN] [1693604644.542250256]: Failed to retrieve type of service /rviz_1693500241430558177/planningscene_planning_scene_monitor/set_parameters
[ WARN] [1693604644.794886449]: Failed to retrieve type of service /roboflow/get_loggers
[ WARN] [1693604645.047990019]: Failed to retrieve type of service /roboflow/set_logger_level
[ERROR] [1693604645.280006653]: Failed to retrieve service type or service description of service /rqt_gui_cpp_node_14210/get_loggers: std::future_error: Broken promise
[ WARN] [1693604645.532430263]: Failed to retrieve type of service /rqt_gui_cpp_node_14210/set_logger_level
[ WARN] [1693604645.785340617]: Failed to retrieve type of service /rqt_gui_cpp_node_54672/get_loggers
[ WARN] [1693604646.038029360]: Failed to retrieve type of service /rqt_gui_cpp_node_54672/set_logger_level
[ERROR] [1693604646.040248199]: Failed to retrieve service type or service description of service /azure1/k4a_nodelet_manager/get_loggers: std::future_error: Broken promise
[ERROR] [1693604646.041587869]: Failed to retrieve service type or service description of service /azure1/k4a_nodelet_manager/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604646.042808514]: Failed to retrieve service type or service description of service /azure1/k4a_nodelet_manager/load_nodelet: std::future_error: Broken promise
[ERROR] [1693604646.043979766]: Failed to retrieve service type or service description of service /azure1/k4a_nodelet_manager/unload_nodelet: std::future_error: Broken promise
[ERROR] [1693604646.045178359]: Failed to retrieve service type or service description of service /azure1/k4a_nodelet_manager/list: std::future_error: Broken promise
2023-09-01T21:44:06.046421617Z [ERROR] [1693604646.046374779]: Failed to retrieve service type or service description of service /robot_2_dx_motion_interface/get_loggers: std::future_error: Broken promise
[ERROR] [1693604646.047603399]: Failed to retrieve service type or service description of service /robot_2_dx_motion_interface/set_logger_level: std::future_error: Broken promise
2023-09-01T21:44:06.048841758Z [ERROR] [1693604646.048795140]: Failed to retrieve service type or service description of service /robot_2_fanuc_rmi_client/get_loggers: std::future_error: Broken promise
[ERROR] [1693604646.049998602]: Failed to retrieve service type or service description of service /robot_2_fanuc_rmi_client/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604646.051181506]: Failed to retrieve service type or service description of service /R2_VeneerCornerObserver/get_loggers: std::future_error: Broken promise
[ERROR] [1693604646.052349872]: Failed to retrieve service type or service description of service /R2_VeneerCornerObserver/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604646.053398030]: Failed to retrieve service type or service description of service /robot_1_dx_motion_interface/get_loggers: std::future_error: Broken promise
[ERROR] [1693604646.054187878]: Failed to retrieve service type or service description of service /robot_1_dx_motion_interface/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604646.054961996]: Failed to retrieve service type or service description of service /robot_1_fanuc_rmi_client/get_loggers: std::future_error: Broken promise
[ERROR] [1693604646.055747836]: Failed to retrieve service type or service description of service /robot_1_fanuc_rmi_client/set_logger_level: std::future_error: Broken promise
[ERROR] [1693604646.132841009]: [WS] handle_accept error: Operation aborted.
[ INFO] [1693604629.821394625]: Loading nodelet /foxglove_bridge of type foxglove_bridge/foxglove_bridge_nodelet to manager foxglove_nodelet_manager with the following remappings:
2023-09-01T21:44:08.961000753Z [ INFO] [1693604629.834298210]: waitForService: Service [/foxglove_nodelet_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1693604629.856897093]: waitForService: Service [/foxglove_nodelet_manager/load_nodelet] is now available.
[ INFO] [1693604648.840659673]: Bond broken, exiting
``` 

- Version: 0.7.1
- Platform: Ubuntu 20:04 - ROS1 Noetic

**Steps To Reproduce**
Launch foxglove-bridge along side instances of RVIZ that are hosted on second machine. 

**Expected Behavior**
Exception is that the node continues on even if its unable to get specific services.

### PR DESCRIPTION
**Pull request by achim-k**
### Public-Facing Changes

Make ROS1 service type retrieval more robust

### Description
For ROS1, foxglove bridge has to retrieve the service type from the service server (by opening a connection) as the ROS master does not store the service type.

This patch makes service type retrieval more robust by
- Fixing the service link object getting out of scope too early
- Better exception handling
- Allowing users to set a custom timeout for service type retrieval

Fixes #262

### CODE REVIEW

File: ros1_foxglove_bridge/include/foxglove_bridge/service_utils.hpp [hunk 1]
```diff
@@ -9,6 +8,6 @@ namespace foxglove_bridge {
  * Opens a socket to the service server and retrieves the service type from the connection header.
  * This is necessary as the service type is not stored on the ROS master.
  */
-std::future<std::string> retrieveServiceType(const std::string& serviceName);
+std::string retrieveServiceType(const std::string& serviceName, int timeout_ms);
```
Comment (jtbandes) [inline ros1_foxglove_bridge/include/foxglove_bridge/service_utils.hpp:11]: better to use a chrono::duration?

File: ros1_foxglove_bridge/src/service_utils.cpp [hunk 2]
```diff
@@ -6,25 +9,29 @@
...
   auto link = ros::ServiceManager::instance()->createServiceServerLink(serviceName, false, "*", "*",
                                                                        {{"probe", "1"}});
-  auto promise = std::make_shared<std::promise<std::string>>();
-  auto future = promise->get_future();
+  std::promise<std::string> promise;
+  auto future = promise.get_future();
 
   link->getConnection()->setHeaderReceivedCallback(
-    [promise = std::move(promise)](const ros::ConnectionPtr&, const ros::Header& header) mutable {
+    [&promise](const ros::ConnectionPtr&, const ros::Header& header) {
```
Comment (jtbandes) [inline ros1_foxglove_bridge/src/service_utils.cpp:19]: I think you could still `std::move` here. (I asked about this on stack overflow long ago: https://stackoverflow.com/questions/58811371/is-it-okay-for-stdfuture-to-outlive-a-stdpromise)

File: ros1_foxglove_bridge/src/service_utils.cpp [hunk 3]
```diff
@@ -6,25 +9,29 @@
...
-        promise->set_exception(std::make_exception_ptr(
+        promise.set_exception(std::make_exception_ptr(
           std::runtime_error("Key 'type' not found in service connection header")));
       }
       return true;
     });
 
-  return future;
+  if (future.wait_for(std::chrono::milliseconds(timeout_ms)) != std::future_status::ready) {
+    throw std::runtime_error("Failed to retrieve service type");
```
Comment (jtbandes) [inline ros1_foxglove_bridge/src/service_utils.cpp:31]: maybe mention "timeout" in the error message?

**Review by jtbandes — APPROVED** [review]

File: ros1_foxglove_bridge/src/service_utils.cpp (hunk 2 above)
Comment (achim-k) [reply ros1_foxglove_bridge/src/service_utils.cpp:19]: I think passing the promise by reference is easier to read in this case. It seems that this is also preferred by clang ThreadSanitizer? Or was this comment just to point out that a std::move was still OK because that's what we used before?
