### PR TITLE
Fix rolling smoke tests crashing

### LINKED ISSUE #304: Rolling smoke test is crashing on exit
On rolling, the smoke test crashes during destruction of the executor, causing a test failure. Something my have changed upstream that causes this behavior. We have to fix this such that PR status checks are working reliably again.

### PR DESCRIPTION
**Pull request by achim-k**
### Changelog
Fix rolling test crashes

### Docs
None

### Description
Fixes the rolling smoke tests crashing due to incorrect executor cleanup. In the end, the only thing missing was a `executor.reset();` at the end of `main`. However I took the opportunity to clean up a little.

Fixes #304

### CODE REVIEW

File: ros2_foxglove_bridge/tests/smoke_test.cpp [hunk 1]
```diff
@@ -759,6 +757,7 @@ int main(int argc, char** argv) {
   const auto testResult = RUN_ALL_TESTS();
   executor->cancel();
   spinnerThread.join();
+  executor.reset();
```
Comment (jtbandes) [inline ros2_foxglove_bridge/tests/smoke_test.cpp:760]: why is this necessary? this is just a shared_ptr right? so even though we already called cancel(), it is problematic to have the object's lifetime last beyond the shutdown() call? Probably could use a comment here because this line seems fairly useless otherwise.

If the lifetime matters so much, can we use `make_unique` instead of `make_shared`?

**Review by jtbandes — APPROVED** [review]

File: ros2_foxglove_bridge/tests/smoke_test.cpp (hunk 1 above)
Comment (achim-k) [reply ros2_foxglove_bridge/tests/smoke_test.cpp]: I think the component manager was still holding on to it which caused issues. I have simplified this now quite a lot and am using the node directly instead of loading it via the component manager.

File: ros2_foxglove_bridge/tests/smoke_test.cpp [hunk 2]
```diff
@@ -732,9 +732,7 @@ int main(int argc, char** argv) {
   testing::InitGoogleTest(&argc, argv);
   rclcpp::init(argc, argv);
 
-  const size_t numThreads = 2;
-  auto executor =
-    rclcpp::executors::MultiThreadedExecutor::make_shared(rclcpp::ExecutorOptions{}, numThreads);
+  auto executor = rclcpp::executors::SingleThreadedExecutor::make_shared();
```
[the remark this answers is not in the document]
Comment (achim-k) [reply ros2_foxglove_bridge/tests/smoke_test.cpp]: no good reason actually, just noticed that it also works with a single threaded executor so I left it
